### ISSUE TITLE
Build failure w/ base-4.7

### ISSUE THREAD

**Issue by hvr** [AshleyYakeley/leapseconds#1]
I noticed your recent package upload to Hackage as it was flagged by the matrix buildbot...

```
Configuring component lib from leapseconds-1.0
Preprocessing library leapseconds-1.0...
[1 of 1] Compiling Data.Time.Clock.LeapSeconds ( src/Data/Time/Clock/LeapSeconds.hs, /tmp/matrix-worker/1479603771/dist-newstyle/build/x86_64-linux/ghc-7.8.4/leapseconds-1.0/build/Data/Time/Clock/LeapSeconds.o )

src/Data/Time/Clock/LeapSeconds.hs:70:18:
    Not in scope: ‘traverse’
    Perhaps you meant ‘reverse’ (imported from Prelude)
```

**Comment by AshleyYakeley** [comment]
If I add leapseconds-1.0.0.1 with the correct base lower bound, will that solve the problem? Or will the buildbot still select leapseconds-1.0 because it matches the base bounds?

**Comment by hvr** [comment]
If you don't plan on adding support for base-4.7, it's enough to just edit the meta-data for the existing 1.0.0 release via http://hackage.haskell.org/package/leapseconds-1.0/leapseconds.cabal/edit (which is needed in any case to keep the buildbot from detecting inaccurate meta-data...)

**Comment by AshleyYakeley** [comment]
Updated leapseconds-1.0 base lower bound to 4.8. This should fix the problem. Thanks!
